article/urls.py
# -*- coding: utf-8 -*-
'''
-----------------------------------
    FileName:     urls
    Description:  
    Author:       瓦都尅
    Date:         2019/11/19
-----------------------------------
'''
from django.conf.urls import url

from . import views

app_name = 'article'
urlpatterns = [
    url(r'(?P<article_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'(?P<article_id>[0-9]+)/edit$', views.edit, name='edit'),
    url(r'^add/', views.add, name='add'),
]

author/urls.py
# -*- coding: utf-8 -*-
'''
-----------------------------------
    FileName:     urls
    Description:  
    Author:       瓦都尅
    Date:         2019/11/20
-----------------------------------
'''
from django.conf.urls import url

from . import views

app_name = 'author'
urlpatterns = [
    url(r'^login/', views.login_view, name='login'),
    url(r'^register/', views.register_view, name='register'),
    url(r'^logout/', views.logout_view, name='logout'),
]

dcblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about_view, name='about'),
    url(r'^article/', include('article.urls'), name='article'),
    url(r'^tag/', include('tag.urls'), name='tag'),
    url(r'^author/', include('author.urls'), name='author'),
]

urlpatterns += staticfiles_urlpatterns()
handler404 = 'dcblog.views.page404'
handler500 = 'dcblog.views.page500'

tag/urls.py
# -*- coding: utf-8 -*-
'''
-----------------------------------
    FileName:     urls
    Description:  
    Author:       瓦都尅
    Date:         2019/11/20
-----------------------------------
'''
from django.conf.urls import url

from . import views

app_name = 'tag'
urlpatterns = [
    url(r'^$', views.tag_index, name='tag_index'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import strip_tags
from mistune import markdown
from django.urls import reverse


from tag.models import Tag


# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100, verbose_name="标题")
    description = models.CharField(max_length=200, null=True, verbose_name="摘要")
    background = models.CharField(max_length=500, null=True, verbose_name="背景图片")
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="作者")
    content = models.TextField(blank=True, verbose_name="正文")
    tag = models.ManyToManyField(Tag, verbose_name="标签")
    read_num = models.IntegerField(default=1000, verbose_name="阅读量")
    pub_date = models.DateTimeField(editable=False, auto_now_add=True, verbose_name="发表时间")

    def save(self, *args, **kwargs):
        # md = markdown.Markdown(extensions=[
        #     'markdown.extensions.extra',
        #     'markdown.extensions.codehilite',
        # ])
        self.description = strip_tags(markdown(self.content))[:80]

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('article:detail', kwargs={'pk': self.pk})

    @property
    def render_content(self):
        return markdown(self.content)

    @property
    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章列表"
        verbose_name_plural = verbose_name
        ordering = ['-pub_date']

tag/models.py
from django.db import models


# Create your models here.


class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True, verbose_name="标签名")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name

tag/views.py
from django.shortcuts import render

# Create your views here.

from .models import Tag


def tag_index(request):
    tags = Tag.objects.all()
    return render(request, 'tag.html', {'tags': tags})

templates/about.html
{% extends 'base.html' %}
{% block header_id %}tag-heading{% endblock %}
{% block header_title %}瓦都尅{% endblock %}
{% block header_subtitle %} 生活不止眼前的苟且, 还有诗和远方. {% endblock %}
{% block background-image %}{{ SITE_ABOUT_BACKGROUND }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <!--<div id="tag_cloud" class="tags">-->
                    <!--<a href="#wx1" style="background-color: rgb(0, 133, 161);">公众号</a>-->
                <!--</div>-->
                <div class="one-tag-list">
                    <span class="post-title" id="whoami">
                            <h2>关于</h2>
                    </span>

                    <div class="post-preview">
                        <a href="#whoami">
                            <h3 class="post-subtitle">
                                <p class="text-white bg-success">root@userInfo:~# whoami</p>
                            </h3>
                            <h4><p>瓦都尅</p></h4>
                            <h3 class="post-subtitle">
                                <p class="text-white bg-success">root@userInfo:~# id</p>
                            </h3>
                            <h4><p>uid=0(安全工程师) gid=0(一个人的安全部) groups=0(某甲方金融公司)</p></h4>
                        </a>
                    </div>

                </div>
                <hr>
                <div class="one-tag-list">
                    <span class="post-title" id="contact">
                            <h2>联系</h2>
                    </span>
                    <div class="post-preview">
                        <a href="#contact">
                            <h3 class="post-subtitle">
                                <p class="text-white bg-success">root@userInfo:~# cat find_me</p>
                            </h3>
                            <h4><p>mail: admin@w2n1ck.com</p></h4>
                            <h4><p>weibo: 瓦都尅</p></h4>
                        </a>
                    </div>

                </div>
                <hr>
                <div class="one-tag-list">
                    <span class="post-title" id="wx">
                            <h2>公众号</h2>
                    </span>
                    <div class="post-preview">
                        <a href="#wx">
                            <h3 class="post-subtitle">
                                <p class="text-white bg-success">root@userInfo:~# fim -a 安全泰式柑汁.jpg</p>
                            </h3>
                            <img src="/static/img/wxgzh.jpg">
                        </a>
                    </div>

                </div>
                <hr>
                <div class="one-tag-list">
                    <span class="post-title" id="friends">
                            <h2>友情链接</h2>
                    </span>
                    <div class="post-preview">
                        <a href="#friends">
                            <h3 class="post-subtitle">
                                <p class="text-white bg-success">root@userInfo:~# ls my_friends</p>
                            </h3>
                            <h4><a class="text-white " href="http://wkh.dropsec.xyz">王小洪: http://wkh.dropsec.xyz</a>
                            </h4>
                            <h4><a class="text-white " href="http://fgp.dropsec.xyz">冯小鹏: http://fgp.dropsec.xyz</a>
                            </h4>
                            <h4><a class="text-white " href="http://blog.neargle.com/">周小斌: http://blog.neargle.com</a>
                            </h4>
                            <h4><a class="text-white " href="http://am4zing.me/">王小岩: http://am4zing.me</a></h4>
                            <h4><a class="text-white " href="http://yangge.me/">杨大成: http://yangge.me</a></h4>
                            <h4><a class="text-white " href="http://www.dropsec.xyz/">Drops: http://www.dropsec.xyz</a>
                            </h4>

                        </a>
                    </div>

                </div>
                <hr>
            </div>
{% endblock %}

templates/article_detail.html
{% extends 'base.html' %}
{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="/static/css/hux-blog.min.css">
{% endblock %}
{% block page_header %}
    <header class="intro-header" style="background-image: url('{% if article.background %}{{ article.background }}{% else %}{{ SITE_ARTICLE_BACKGROUND }}{% endif %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        {% if tags %}
                            <div class="tags">
                                {% for tag in tags %}
                                    <a class="tag" href="{% url 'tag:tag_index' %}#{{ tag.name }}"
                                       title="{{ tag.name }}">{{ tag.name }}</a>
                                {% endfor %}
                            </div>
                        {% endif %}
                        <h1>{{ article.title }}</h1>
                        <!--{% if article.description %}-->
                            <!--<h2 class="subheading">{{ article.description }}</h2>-->
                        <!--{% endif %}-->
                        <span class="meta">Posted by <a
                                href="#">{{ article.author.username }}</a> on {{ article.pub_date }}</span>
                        {% if not user.is_anonymous and user.is_superuser or user == article.author %}
                            <br>
                            <span class="meta">
                            <a href="{% url 'article:edit' article.id %}">编辑文章</a>
                        </span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}
{% block content %}
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    {{ article.render_content | safe }}
                </div>
            </div>
        </div>
    </article>
{% endblock %}

{% block toc %}
  <!--{% if post.toc %}-->
    <div class="widget widget-content">
      <h3 class="widget-title">文章目录</h3>
      <div class="toc">
        <ul>
          {{ post.toc|safe }}
        </ul>
      </div>
    </div>
  <!--{% endif %}-->
{% endblock toc %}

{% block script %}
    {{ block.super }}
    <!-- Code Javascript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.10.0/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}{{ SITE_NAME }}{% endblock %}</title>


    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/clean-blog.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.10.0/styles/default.min.css">
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>
    <link href="//fonts.googleapis.com/css?family=Lato:300,300italic,400,400italic,700,700italic|Fira Mono:300,300italic,400,400italic,700,700italic&subset=latin,latin-ext"
          rel='stylesheet' type='text/css'>

    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="https://cdn.bootcss.com/highlight.js/9.15.8/styles/github.min.css" rel="stylesheet">

    <style>
        .codehilite {
            padding: 0;
        }

        /* for block of numbers */
        .hljs-ln-numbers {
            -webkit-touch-callout: none;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;

            text-align: center;
            color: #ccc;
            border-right: 1px solid #CCC;
            vertical-align: top;
            padding-right: 5px;
        }

        .hljs-ln-n {
            width: 30px;
        }

        /* for block of code */
        .hljs-ln .hljs-ln-code {
            padding-left: 10px;
            white-space: pre;
        }
    </style>

    {% block head %}{% endblock %}
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">{{ SITE_NAME }}</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'index' %}">首页</a>
                </li>
                <li>
                    <a href="{% url 'tag:tag_index' %}">标签</a>
                </li>
                <li>
                    <a href="{% url 'about' %}#wx">公众号</a>
                </li>
                <li>
                    <a href="{% url 'about' %}">关于</a>
                </li>
                {% if user.is_anonymous %}
                    <li><a href="{% url 'author:login' %}">登陆</a></li>
                    <li><a href="{% url 'author:register' %}">注册</a></li>
                {% else %}
                    <li><a href="{% url 'article:add' %}">添加文章</a></li>
                    <li><a href="{% url 'author:logout' %}">注销</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
{% block page_header %}
    <header class="intro-header"
            style="background-image: url('{% block background-image %}{{ SITE_HOME_BACKGROUND }}{% endblock %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" id="{% block header_id %}site-heading{% endblock %}">
                        <h2>{% block header_title %}{{ SITE_AUTHOR }}{% endblock %}</h2>
                        <hr class="small">
                        <span class="subheading">{% block header_subtitle %}{{ SITE_DESCRIPTION }}{% endblock %}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
{% endblock %}
{% block toc %}
{% endblock %}

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <ul class="list-inline text-center">
                    <li>
                        <a href="{{ SITE_ZHIHU_URL }}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa  fa-stack-1x fa-inverse">知</i>
                                </span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ SITE_GITHUB_URL }}">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; {{ SITE_AUTHOR }} Powered by <a href="https://github.com/w2n1ck/dcblog">DCblog</a></p>
            </div>
        </div>
    </div>
</footer>

{% block script %}
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/static/js/clean-blog.min.js"></script>
    <script src="https://cdn.bootcss.com/highlight.js/9.15.8/highlight.min.js"></script>
    <script src="https://cdn.bootcss.com/highlightjs-line-numbers.js/2.7.0/highlightjs-line-numbers.min.js"></script>
    <script>
        hljs.initHighlightingOnLoad();
        hljs.initLineNumbersOnLoad();
    </script>
{% endblock %}
</body>
</html>

templates/error.html
{% extends 'base.html' %}

{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="/static/css/hux-blog.min.css">
{% endblock %}
{% block page_header %}
    <header class="intro-header" style="background-image: url('{{ SITE_ERROR_BACKGROUND }}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading" id="tag-heading">
                        <h1>{{ status_code }}</h1>
                        <span class="subheading">{{ message }}</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <script>document.body.classList.add('page-fullscreen');</script>
{% endblock %}

templates/generic_form.html
{% extends "base.html" %}
{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="/static/css/hux-blog.min.css">
{% endblock %}

{% block background-image %}{% spaceless %}
    {% if background %}
        {{ background }}
    {% else %}
        {{ SITE_FORM_BACKGROUND }}
    {% endif %}
{% endspaceless %}{% endblock %}
{% if header_id %}
    {% block header_id %}{{ header_id }}{% endblock %}
{% endif %}
{% block header_title %}{{ title }}{% endblock %}
{% block header_subtitle %}{{ subtitle }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <form name="simpleform" id="simpleForm" method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                {{ field.label_tag }}
                                {{ field.as_widget }}
                            </div>
                        </div>
                        <p class="help-block text-danger">
                            {% if field.errors %}
                                <ul role="alert">
                                    {% for error in field.errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            {% endif %}
                        </p>
                    {% endfor %}
                    <div id="success">
                        {% if messages %}
                            {% for msg in messages %}
                                <div class="alert alert-danger">
                                    <button type="button" class="close" data-dismiss="alert"
                                            aria-hidden="true"></button>
                                    <strong>{{ msg }}</strong></div>
                            {% endfor %}
                        {% endif %}
                    </div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">{{ submit }}</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script src="/static/js/jqBootstrapValidation.js"></script>
    <script src="/static/js/contact_me.js"></script>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
<!-- Main Content -->
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% for article in articles %}
                    <div class="post-preview">
                        <a href="{% url 'article:detail' article.id %}">
                            <h2 class="post-title">
                                {{ article.title }}
                            </h2>
                            <h4 class="post-subtitle">
                                {% if article.description %}
                                    {{ article.description }}
                                {% endif %}
                            </h4>
                        </a>
                        <p class="post-meta">Posted by <a
                                href="#">{{ article.author.username }}</a> {{ article.pub_date }}</p>
                    </div>
                    <hr>
                {% endfor %}
                <!-- Pager -->
                <ul class="pager">
                    {% if articles.has_previous %}
                        <li class="previous">
                            <a href="?page={{ articles.previous_page_number }}">← Newer Posts</a>
                        </li>
                    {% endif %}
                    {% if articles.has_next %}
                        <li class="next">
                            <a href="?page={{ articles.next_page_number }}">Older Posts &rarr;</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <hr>
{% endblock %}

templates/tag.html
{% extends 'base.html' %}
{% block head %}
    {{ block.super }}
    <link rel="stylesheet" href="/static/css/hux-blog.min.css">
{% endblock %}


{% block header_title %}标签{% endblock %}
{% block header_subtitle %}
<div id="tag_cloud" class="tags">
    {% for tag in tags %}
    <a href="#{{ tag.name }}" style="background-color: rgb(0, 133, 161);">{{ tag.name }}</a>
    {% endfor %}
</div>
{% endblock %}
{% block background-image %}{{ SITE_TAG_BACKGROUND }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% for tag in tags %}
                    <div class="one-tag-list">
                        <span class="fa fa-tag listing-seperator" id="{{ tag.name }}">
                            <span class="tag-text">{{ tag.name }}</span>
                        </span>
                        {% for article in tag.article_set.all %}
                            <div class="post-preview">
                                <a href="{% url 'article:detail' article.id %}">
                                    <h2 class="post-title">
                                        {{ article.title }}
                                    </h2>
                                    <h3 class="post-subtitle">
                                        {{ article.description }}
                                    </h3>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
                <hr>
            </div>
{% endblock %}